ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- 1. T?o user LAB1
CREATE USER LAB1 IDENTIFIED BY 123;

-- 2. C?p quy?n
GRANT CONNECT, RESOURCE TO LAB1;
GRANT UNLIMITED TABLESPACE TO LAB1;

-- --- T?O B?NG ---
CREATE TABLE HANGHANGKHONG (
    MAHANG VARCHAR2(5) PRIMARY KEY,
    TENHANG VARCHAR2(50),
    NGTL DATE,
    DUONGBAY NUMBER
);

CREATE TABLE CHUYENBAY (
    MACB VARCHAR2(10) PRIMARY KEY,
    MAHANG VARCHAR2(5),
    XUATPHAT VARCHAR2(50),
    DIEMDEN VARCHAR2(50),
    BATDAU DATE,
    TGBAY NUMBER(4,1),
    CONSTRAINT FK_CB_HANG FOREIGN KEY (MAHANG) REFERENCES HANGHANGKHONG(MAHANG)
);

CREATE TABLE NHANVIEN (
    MANV VARCHAR2(5) PRIMARY KEY,
    HOTEN VARCHAR2(50),
    GIOITINH VARCHAR2(5),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR2(20)
);

CREATE TABLE PHANCONG (
    MACB VARCHAR2(10),
    MANV VARCHAR2(5),
    NHIEMVU VARCHAR2(50),
    PRIMARY KEY (MACB, MANV),
    CONSTRAINT FK_PC_CB FOREIGN KEY (MACB) REFERENCES CHUYENBAY(MACB),
    CONSTRAINT FK_PC_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

--Câu 2: NH?P D? LI?U ---
-- HANGHANGKHONG
INSERT INTO HANGHANGKHONG VALUES ('VN', 'Vietnam Airlines', TO_DATE('15/01/1956','DD/MM/YYYY'), 52);
INSERT INTO HANGHANGKHONG VALUES ('VJ', 'Vietjet Air', TO_DATE('25/12/2011','DD/MM/YYYY'), 33);
INSERT INTO HANGHANGKHONG VALUES ('BL', 'Jetstar Pacific Airlines', TO_DATE('01/12/1990','DD/MM/YYYY'), 13);

-- CHUYENBAY
INSERT INTO CHUYENBAY VALUES ('VN550', 'VN', 'TP.HCM', 'Singapore', TO_DATE('20/12/2025 13:15','DD/MM/YYYY HH24:MI'), 2);
INSERT INTO CHUYENBAY VALUES ('VJ331', 'VJ', 'Ðà N?ng', 'Vinh', TO_DATE('28/12/2025 22:30','DD/MM/YYYY HH24:MI'), 1);
INSERT INTO CHUYENBAY VALUES ('BL696', 'BL', 'TP.HCM', 'Ðà L?t', TO_DATE('24/12/2025 06:00','DD/MM/YYYY HH24:MI'), 0.5);

-- NHANVIEN
INSERT INTO NHANVIEN VALUES ('NV01', 'Lâm Vãn B?n', 'Nam', TO_DATE('10/09/1991','DD/MM/YYYY'), TO_DATE('05/06/2021','DD/MM/YYYY'), 'Phi công');
INSERT INTO NHANVIEN VALUES ('NV02', 'Dýõng Th? L?c', 'N?', TO_DATE('22/03/1989','DD/MM/YYYY'), TO_DATE('12/11/2020','DD/MM/YYYY'), 'Ti?p viên');
INSERT INTO NHANVIEN VALUES ('NV03', 'Hoàng Thanh Tùng', 'Nam', TO_DATE('29/07/1995','DD/MM/YYYY'), TO_DATE('11/04/2022','DD/MM/YYYY'), 'Ti?p viên');

-- PHANCONG
INSERT INTO PHANCONG VALUES ('VN550', 'NV01', 'Cõ trý?ng');
INSERT INTO PHANCONG VALUES ('VN550', 'NV02', 'Ti?p viên');
INSERT INTO PHANCONG VALUES ('BL696', 'NV03', 'Ti?p viên trý?ng');

COMMIT;

-- Câu 3: Chuyên môn ch? là Phi công ho?c Ti?p viên
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_CHUYENMON CHECK (CHUYENMON IN ('Phi công', 'Ti?p viên'));

-- Câu 4: Ngày bay ph?i sau ngày thành l?p h?ng (Dùng Trigger)
CREATE OR REPLACE TRIGGER TRG_CHECK_NGAYBAY
BEFORE INSERT OR UPDATE ON CHUYENBAY
FOR EACH ROW
DECLARE
    v_ngtl DATE;
BEGIN
    SELECT NGTL INTO v_ngtl FROM HANGHANGKHONG WHERE MAHANG = :NEW.MAHANG;
    IF :NEW.BATDAU <= v_ngtl THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ngày bay ph?i sau ngày thành l?p h?ng!');
    END IF;
END;

-- Câu 5: Nhân viên sinh tháng 07
SELECT * FROM NHANVIEN WHERE EXTRACT(MONTH FROM NGSINH) = 7;

-- Câu 6: Chuy?n bay có nhi?u nhân viên nh?t
SELECT MACB, COUNT(MANV) AS SL_NV FROM PHANCONG 
GROUP BY MACB 
ORDER BY SL_NV DESC FETCH FIRST 1 ROW ONLY;

-- Câu 7: S? chuy?n bay xu?t phát t? Ðà N?ng có < 2 nhân viên (theo t?ng h?ng)
SELECT H.TENHANG, COUNT(C.MACB)
FROM HANGHANGKHONG H
JOIN CHUYENBAY C ON H.MAHANG = C.MAHANG
JOIN PHANCONG P ON C.MACB = P.MACB
WHERE C.XUATPHAT = N'Ðà N?ng'
GROUP BY H.TENHANG, C.MACB
HAVING COUNT(P.MANV) < 2;

-- Câu 8: Nhân viên tham gia T?T C? chuy?n bay
SELECT HOTEN FROM NHANVIEN NV
WHERE NOT EXISTS (
    SELECT * FROM CHUYENBAY CB
    WHERE NOT EXISTS (
        SELECT * FROM PHANCONG PC
        WHERE PC.MACB = CB.MACB AND PC.MANV = NV.MANV
    )
);